#!/usr/bin/env python
# -*- coding: utf-8 -*-

from mightywatt import MightyWatt
from mightywatt.webapp import MightyWattWebServerInterface

def main():
    import argparse
    parser = argparse.ArgumentParser(description='MightyWatt Web Server')
    parser.add_argument('serial_port', help='The serial port to connect to')
    parser.add_argument('--port', '-p', default=8001, help='Web server port')
    parser.add_argument('--ipv6', '-6', action='store_true', help='IPv6 mode')
    parser.add_argument('--debug', '-d', action='store_true', help='Debug mode')
    args = parser.parse_args()
    try:
        try:
            mw = MightyWatt(args.serial_port)
        except:
            parser.error("couldn't connect to the device.")
        mw.set_update_rate(100)
        mwwsi = MightyWattWebServerInterface(mw)
        if args.debug:
            mwwsi.run(host='0.0.0.0', port=args.port, debug=True)
        else:
            if args.ipv6:
                # CherryPy is Python3 ready and has IPv6 support:
                mwwsi.run(host='::', server='cherrypy', port=args.port)
            else:
                mwwsi.run(host='0.0.0.0', server='cherrypy', port=args.port)
    except KeyboardInterrupt:
        print('Ctrl-C pressed. Exiting...')
    finally:
        try:
            mw.close()
        except:
            pass

if __name__ == "__main__":
    main()
